{% set name = "camelot-py" %}
{% set version = "0.7.1" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://github.com/socialcopsdev/camelot/archive/v{{ version }}.tar.gz
  sha256: 80e7a527ece247287f15e3200780199ed0cebecf04e84f2549f32b6627701dae

build:
  number: 0
  entry_points:
    - camelot = camelot.cli:cli
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - tk
    - ghostscript  # [not win]
    - click >=6.7
    - matplotlib >=2.2.3
    - numpy >=1.13.3
    - opencv >=3.2.0
    - openpyxl >=2.5.8
    - pandas >=0.23.4
    - pdfminer.six >=20170720
    - pycryptodome
    - pypdf2 >=1.26.0
    - python

test:
  imports:
    - camelot
  commands:
    - camelot --help

about:
  home: http://camelot-py.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: PDF Table Extraction for Humans.

extra:
  recipe-maintainers:
    - vinayak-mehta
