{% set name = "camelot-py" %}
{% set author = "socialcopsdev" %}
{% set version = "0.7.2" %}
{% set sha256 = "2386d25df072759ab6a7a1c075ddf94eb2697f840dfa5f95b0c56c6c9c2a49c0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://github.com/{{ author }}/{{name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - camelot = camelot.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - tk
    - ghostscript  # [not win]
    - click >=6.7
    - matplotlib >=2.2.3
    - numpy >=1.13.3
    - opencv >=3.2.0
    - openpyxl >=2.5.8
    - pandas >=0.23.4
    - pdfminer.six >=20181108
    - pycryptodome
    - pypdf2 >=1.26.0
    - python

test:
  imports:
    - camelot
  commands:
    - camelot --help

about:
  home: http://camelot-py.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: PDF Table Extraction for Humans.

extra:
  recipe-maintainers:
    - vinayak-mehta
