{% set version = "0.7.3" %}

package:
  name: camelot-py
  version: "{{ version }}"

source:
  url: https://github.com/socialcopsdev/camelot/archive/v{{ version }}.tar.gz
  sha256: 60da7906ec5b48984d95abcbd97beff9c3e80c93b47361205def214d507a240c

build:
  number: 1
  entry_points:
    - camelot = camelot.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - tk
    - ghostscript  # [not win]
    - click >=6.7
    - matplotlib-base >=2.2.3
    - numpy >=1.13.3
    - opencv >=3.2.0
    - openpyxl >=2.5.8
    - pandas >=0.23.4
    - pdfminer.six >=20181108
    - pycryptodome
    - pypdf2 >=1.26.0
    - python

test:
  imports:
    - camelot
  commands:
    - camelot --help

about:
  home: http://camelot-py.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: PDF Table Extraction for Humans.

extra:
  recipe-maintainers:
    - vinayak-mehta
